# Homebrew Cask for glassy, a fast GPU-accelerated terminal emulator.
# This repo is its own tap, so:
#   brew tap alliecatowo/glassy https://github.com/alliecatowo/glassy
#   brew install --cask glassy
#
# This is the recommended macOS install path: it puts glassy.app in
# /Applications AND symlinks the CLI binary embedded in the bundle
# (Contents/MacOS/glassy — the same binary that runs the GUI) onto PATH via
# the `binary` artifact below, so installing the cask alone gets you both
# the app and the `glassy` command with no separate Formula/glassy.rb
# install needed. Formula/glassy.rb still exists for Linux (Casks are
# macOS-only) and for anyone who explicitly wants a headless CLI-only build.
#
# The version/sha256 fields below are generated by .github/workflows/release.yml's
# update-homebrew job from Casks/glassy.rb.tmpl on every release, which
# overwrites this file. Edit the .tmpl, not this file — edits here get
# clobbered on the next release (see Formula/glassy.rb.tmpl for why this
# renders fresh from a template instead of sed-patching in place).
cask "glassy" do
  arch arm: "aarch64", intel: "x86_64"

  version "0.4.3"
  sha256 arm:   "cac77407b3dd685d534acf80266d1dbeae169bfc6ce7844ba9d65f734ad368a3",
         intel: "3a4a019cb1b8e00834590a85362c2adf378be57bffc4a3d38074e9055091161b"

  url "https://github.com/alliecatowo/glassy/releases/download/v0.4.3/glassy-#{version}-macos-#{arch}.dmg"
  name "glassy"
  desc "Fast, minimal GPU-accelerated terminal emulator written in Rust"
  homepage "https://github.com/alliecatowo/glassy"

  depends_on macos: :big_sur

  app "glassy.app"
  binary "#{appdir}/glassy.app/Contents/MacOS/glassy"

  # glassy is ad-hoc signed (needed just to execute at all on Apple Silicon)
  # but not notarized — no paid Apple Developer Program account behind this
  # project. Without this, Gatekeeper blocks first launch with "Apple could
  # not verify 'glassy' is free of malware", since brew --cask (unlike brew
  # install of a plain Formula) deliberately quarantines installed apps.
  # Scoped to glassy.app only — this has no effect on Gatekeeper's handling
  # of anything else on the system.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/glassy.app"]
  end

  zap trash: [
    "~/.local/state/glassy",
    "~/Library/Application Support/glassy",
    "~/Library/Caches/glassy",
  ]

  caveats do
    <<~EOS
      glassy is ad-hoc signed but not notarized by Apple (no paid Developer
      Program account behind this project yet). This cask clears the
      com.apple.quarantine flag on #{appdir}/glassy.app during install so
      Gatekeeper doesn't block first launch with "Apple could not verify
      'glassy' is free of malware". If you'd rather see that warning and
      decide for yourself, download the .dmg from the Releases page instead:
        https://github.com/alliecatowo/glassy/releases
    EOS
  end
end
