# Homebrew Cask for glassy, a fast GPU-accelerated terminal emulator.
# This repo is its own tap, so:
#   brew tap alliecatowo/glassy https://github.com/alliecatowo/glassy
#   brew install --cask glassy
#
# This is the recommended macOS install path: it puts glassy.app in
# /Applications AND symlinks the CLI binary embedded in the bundle
# (Contents/MacOS/glassy — the same binary that runs the GUI) onto PATH via
# the `binary` artifact below, so installing the cask alone gets you both
# the app and the `glassy` command with no separate Formula/glassy.rb
# install needed. Formula/glassy.rb still exists for Linux (Casks are
# macOS-only) and for anyone who explicitly wants a headless CLI-only build.
#
# The version/sha256 fields below are generated by .github/workflows/release.yml's
# update-homebrew job from Casks/glassy.rb.tmpl on every release, which
# overwrites this file. Edit the .tmpl, not this file — edits here get
# clobbered on the next release (see Formula/glassy.rb.tmpl for why this
# renders fresh from a template instead of sed-patching in place).
cask "glassy" do
  arch arm: "aarch64", intel: "x86_64"

  version "0.4.2"
  sha256 arm:   "c9579cac1779f78814a875c7d569188d9045cbceaa1fe377f5b95feb4e3fe39c",
         intel: "157bffe4ef662808ba6d86ed4e67f92424e6c52eddd902490e2b7b05cdb4e471"

  url "https://github.com/alliecatowo/glassy/releases/download/v0.4.2/glassy-#{version}-macos-#{arch}.dmg"
  name "glassy"
  desc "Fast, minimal GPU-accelerated terminal emulator written in Rust"
  homepage "https://github.com/alliecatowo/glassy"

  depends_on macos: :big_sur

  app "glassy.app"
  binary "#{appdir}/glassy.app/Contents/MacOS/glassy"

  zap trash: [
    "~/.local/state/glassy",
    "~/Library/Application Support/glassy",
    "~/Library/Caches/glassy",
  ]
end
