# Homebrew formula for glassy, a fast GPU-accelerated terminal emulator.
# This repo is its own tap, so:
#   brew tap alliecatowo/glassy https://github.com/alliecatowo/glassy
#   brew install glassy          # latest tagged release
#   brew install --HEAD glassy   # build from main (requires Rust)
#
# The version/sha256 fields below are generated by .github/workflows/release.yml's
# update-homebrew job from Formula/glassy.rb.tmpl on every release, which
# overwrites this file. Edit the .tmpl, not this file — edits here get
# clobbered on the next release. (The old approach sed-patched this file's
# sentinels in place, which only works once: after the tokens are consumed,
# the next release's sed finds nothing left to replace and silently stops
# updating. Rendering fresh from an untouched .tmpl every time avoids that.)
#
# On macOS, stable installs fetch the prebuilt per-arch binary that
# build-macos already uploads as a release asset (glassy-aarch64-macos /
# glassy-x86_64-macos) instead of compiling from source — `cargo install`
# here took several minutes (lto = "fat" + codegen-units = 1 in Cargo.toml),
# while downloading an already-built binary takes seconds. Linux stable
# installs still build from the top-level source tarball (no prebuilt Linux
# binary asset is wired up here yet). `--HEAD` always builds from source on
# any OS, since there's no prebuilt asset for an arbitrary main commit.
class Glassy < Formula
  desc "Fast, minimal GPU-accelerated terminal emulator written in Rust"
  homepage "https://github.com/alliecatowo/glassy"
  url "https://github.com/alliecatowo/glassy/releases/download/v0.4.2/glassy-0.4.2-src.tar.gz"
  version "0.4.2"
  sha256 "b3a926e1a8b4b1ece41b1f47d72d60f049a53e2079bffcf2413721cb341603cc"
  license "MIT"

  head do
    url "https://github.com/alliecatowo/glassy.git", branch: "main"
    depends_on "pkg-config" => :build
    depends_on "rust" => :build
  end

  # macOS-only override: swap the default source tarball for a prebuilt
  # per-arch binary. Homebrew resolves on_arm/on_intel against the host's
  # arch, so `brew install glassy` on macOS never touches the url/sha256 above.
  on_macos do
    on_arm do
      url "https://github.com/alliecatowo/glassy/releases/download/v0.4.2/glassy-aarch64-macos"
      sha256 "e2029400f9cbb2336a00907e4f003a240de66de50bbf1d9c268c98f388a82aed"
    end
    on_intel do
      url "https://github.com/alliecatowo/glassy/releases/download/v0.4.2/glassy-x86_64-macos"
      sha256 "39b2e07adad16b3ffc6ad1022273d51a19891126c4d99840794be2969517fca7"
    end
  end

  on_linux do
    depends_on "pkg-config" => :build
    depends_on "rust" => :build
    depends_on "fontconfig"
  end

  def install
    if OS.mac? && !build.head?
      # Downloaded as a bare (non-archived) binary named glassy-<arch>-macos;
      # GitHub release assets carry no exec bit, hence the explicit chmod.
      bin.install Dir["glassy-*-macos"].first => "glassy"
      chmod 0755, bin/"glassy"
    else
      system "cargo", "install", *std_cargo_args
    end
  end

  # Install man page if present.
  def post_install
    man1.mkpath
    man1.install "extra/glassy.1" if File.exist?("extra/glassy.1")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/glassy --version 2>&1")
  end
end
