# Homebrew formula for glassy, a fast GPU-accelerated terminal emulator.
#
# To install from this formula directly (build from source):
#   brew install --build-from-source ./packaging/homebrew/glassy.rb
#
# The version/sha256 fields below are generated by .github/workflows/release.yml's
# update-homebrew job from packaging/homebrew/glassy.rb.tmpl on every
# release, which overwrites this file. Edit the .tmpl, not this file —
# edits here get clobbered on the next release (see Formula/glassy.rb.tmpl
# for why this renders fresh from a template instead of sed-patching in
# place, which is how this file ended up stuck at v0.2.0-rc2 for three
# releases).
class Glassy < Formula
  desc "Fast, minimal GPU-accelerated terminal emulator written in Rust"
  homepage "https://github.com/alliecatowo/glassy"
  # url points at the release-uploaded source tarball asset so it matches the
  # sha256 the workflow computes (the GitHub auto-archive tarball has a different
  # hash). Unlike Formula/glassy.rb (this repo's own tap, which installs a
  # prebuilt binary for speed), this formula deliberately always builds from
  # source — that's the point of it: a homebrew-core submission requires a
  # build-from-source formula, since core disallows vendored binaries.
  url "https://github.com/alliecatowo/glassy/releases/download/v0.4.2/glassy-0.4.2-src.tar.gz"
  version "0.4.2"
  sha256 "b3a926e1a8b4b1ece41b1f47d72d60f049a53e2079bffcf2413721cb341603cc"
  license "MIT"
  head "https://github.com/alliecatowo/glassy.git", branch: "main"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
  end

  # Install man page if present.
  def post_install
    man1.mkpath
    man1.install "extra/glassy.1" if File.exist?("extra/glassy.1")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/glassy --version 2>&1")
  end
end
